name: boardbit
description: 'Application for tracking your board game stats and plays.'

publish_to: 'none'

version: 1.0.0+100

environment:
  sdk: ^3.5.1

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^1.1.5
  cloud_firestore: ^4.14.0
  cloud_firestore_odm: ^1.0.0-dev.83
  collection: ^1.18.0
  dio: ^5.6.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.4.7
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  hugeicons: ^0.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  package_info_plus: ^8.0.2
  riverpod_annotation: ^2.3.5
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  stack_trace: ^1.11.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  vector_graphics: ^1.1.11+1
  xml2json: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.4.0
  cloud_firestore_odm_generator: ^1.0.0-dev.85
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  very_good_analysis: ^6.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app_icon/app_icon.png'
  min_sdk_android: 24 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffe3'
  adaptive_icon_foreground: 'assets/app_icon/app_icon_android.png'

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
